### PR TITLE
Add Github action to build the repo without Conda

### PR DESCRIPTION
**Pull request by fcladera**

### CODE REVIEW

**Comment by versatran01** [comment]
xtl/xtensor is optional, you can remove it from ci

**Comment by fcladera** [comment]
Should I modify the `CMakeLists.txt`?

**Comment by versatran01** [comment]
sorry, gtest/benchmark are actually required, but xtensor is optional

**Comment by versatran01** [comment]
Let me know when it can be merged

**Comment by fcladera** [comment]
This is ready to merge. I removed xtensor. There are a few warnings when building, would you like to add compilation flags or do something else to get rid of those?

https://github.com/fcladera/dsol/runs/7508285696?check_suite_focus=true

**Comment by versatran01** [comment]
Most of these warnings are from ros?

**Comment by fcladera** [comment]
Yes, that's correct. Most warnings are from ros. There are a few implicit conversions form `int` to `double` and viceversa, one unused parameter in `FrameAligner::Solve`.

I will update the the build file with your suggestions.

**Comment by fcladera** [comment]
Modifications are ready.

**Comment by versatran01** [comment]
Thanks, merged.

**Pull request merged**
